twig:

    default_path: '%kernel.project_dir%/templates'
    globals:
        uploadedFilesPath: '\uploads\images\'
        uploadedModifiedFilesPath: '\uploads\modified\'
when@test:
    twig:
        strict_variables: true
